name: python-sdk

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        python-version: [3.5,3.6,3.7]
        tf-version: [1.14.0,1.15.0]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v1
      - name: Verify MySQL connection from host
        run: |
          sudo apt update
          sudo apt-get install -y mysql-client
          sudo service mysql restart
          # default mysql account and password in github actions
          mysql -uroot -proot -e "SHOW DATABASES"
      - name: Setup submarine database
        run: |
          mysql -uroot -proot -e "create database submarine_test;"
          mysql -uroot -proot -e "CREATE USER 'submarine_test'@'%' IDENTIFIED BY 'password_test';"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'submarine_test'@'%';"
          mysql -uroot -proot -e "use submarine_test; source ./docs/database/submarine.sql; show tables;"
      - name: Setup python environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ./submarine-sdk/pysubmarine/.
          pip install tensorflow==${{ matrix.tf-version }}
          pip install torch==1.4.0
          pip install -r ./submarine-sdk/pysubmarine/github-actions/test-requirements.txt
          pip install -r ./submarine-sdk/pysubmarine/github-actions/lint-requirements.txt
      - name: Check python sdk code style
        if: matrix.python-version == '3.6'
        run: |
          ./submarine-sdk/pysubmarine/github-actions/lint.sh
      - name: Test with pytest
        run: |
          pytest --cov=submarine -vs


